version: '3'
services:

 web:
   build: web/
   restart: always

   ports:
     - "8080:80"
   volumes:
     - ./web/www:/var/www/html

 postgresql:
   restart: always
   build: postgresql/

   volumes:
     - ./postgresql/data:/data

   environment:
     POSTGRES_DATA_FOLDER: /data

   ports:
     - "6432:5432"
